### ISSUE TITLE
Ajout de Omeka

### ISSUE THREAD

**Issue by pcouchet** [DISIC/sill#1]
Serait-il possible d'intégrer à la liste les 2 logiciels Omeka : https://omeka.org/
- Omeka Classic
- Omeka S
- Une liste des fonctionnalités et usages francophones  :  https://archivengines.wordpress.com/omeka/

Omeka Classic et Omeka S sont deux gestionnaires de contenus adaptés pour la mise en ligne de fichiers présentant un intérêt littéraire, scientifique, patrimonial ou archivistique.

**Comment by bzg** [comment]
Merci pour la proposition.

Je ne suis pas en position de décider de l'ajout ou non d'une "souche" dans le SILL, c'est du ressort des groupes qui l'élaborent et le publient - mais je note bien la demande et la fais suivre.

S'il fallait trouver un organisme public référent pour ce logiciel, est-ce que https://www.huma-num.fr vous semblerait le bon ?

**Comment by bzg** [comment]
Les propositions d'ajout dans le SILL vont être gérées autrement à partir de 2022.  Nous avons bien noté celle-ci.
