### ISSUE TITLE
Proposition d'aide : Référent pour TYPO3

### ISSUE THREAD

**Issue by jonathanPalais** [DISIC/sill#100]
Bonjour,

Le Palais de la découverte. 
Je suis personnel ITRF (MESRI)

TYPO3

J'envoie un mail plus complet à bastien.guerry@data.gouv.fr

**Comment by bzg** [comment]
Bienvenue sur les listes mimo@ et sill-mainteneurs@ ! TYPO3 est en recommandé, je ferme le ticket.
