### ISSUE TITLE
Nouveau logiciel : TRACIM

### ISSUE THREAD

**Issue by JacquesBraquet** [DISIC/sill#102]
Tracim propose tous les outils nécessaires au travail en équipe et à la gestion des connaissances au sein d'une application unique.
Ses outils bureautiques collaboratifs peuvent être utilisés, entre autre, pour la collaboration et la coordination d'équipes pédagogiques.

**Comment by bzg** [comment]
Bonjour, merci pour votre proposition.

Je vous recommande de lire [cette page](https://disic.github.io/sill/) pour comprendre la façon dont un logiciel peut être ajouté au SILL.  Si vous trouvez un référent SILL volontaire dans une administration publique utilisatrice de TRACIM, n'hésitez pas à nous tenir au courant.

**Comment by bzg** [comment]
Tracim est dans le SILL : https://sill.etalab.gouv.fr/fr/software?id=213

Il manque une version minimale recommandée, n'hésite pas à m'écrire directement pour préciser.
