### ISSUE TITLE
Proposition d'aide : pour le logiciel fusiondirectory

### ISSUE THREAD

**Issue by amichon69** [DISIC/sill#103]
Bonjour,
Je voudrais vous proposer mon aide pour le logiciel 

Fusiondirectory : https://github.com/DISIC/sill/issues/41

J'appartiens au

Ministère de l'enseignement supèrieur, de la recherche et de l'innovation

A bientot
Alexis

**Comment by bzg** [comment]
FusionDirectory est désormais dans le SILL: https://sill.etalab.gouv.fr/fr/software?id=206
