### ISSUE TITLE
Proposition d'aide : référent TRACIM

### ISSUE THREAD

**Issue by JacquesBraquet** [DISIC/sill#104]
Je suis enseignant référent numérique dans un collège. Nous utilisons TRACIM pour coordonner l'équipe pédagogique pendant le confinement (suivi élève, planning des classes, liens classes virtuelles..).

Je veux bien être référent SILL pour TRACIM si ce rôle n'est pas trop chronophage et s'il n'y a pas de compétences techniques spécifiques à avoir.

**Comment by bzg** [comment]
Tracim est dans le SILL : https://sill.etalab.gouv.fr/fr/software?id=213

Il manque une version minimale recommandée, n'hésite pas à m'écrire directement pour préciser.
