### ISSUE TITLE
 Logiciel CodiMD : fork me, forever !

### ISSUE THREAD

**Issue by dzc34** [DISIC/sill#107]
Problème de fork avec nom identique... 

voir: https://github.com/DISIC/sill/commit/5a5635d97de9e60e36b0615116ff4d7c39610f6e
>  Mise à jour de la version de codimd utilisé à la DINUM
> 
> Suppression du lien avec le comptoir du libre car le comptoir
> référence un fork du projet utilisé par la DINUM.  À discuter
> pour être sûr de savoir quoi référencer.

```diff
-180,CodiMD,Outil de partage de notes,2020,O,,,,,362,AGPL-3.0,Orchestration et logique métier,Outil collaboratif,En version 1.4.1 à la DINUM,MIMO,
+180,CodiMD,Outil de partage de notes,2020,O,,,,,,AGPL-3.0,Orchestration et logique métier,Outil collaboratif,En version 1.6.1 à la DINUM,MIMO,
```
 ----------------------

2 dépôts  :
- https://github.com/hackmdio/codimd 
- https://github.com/codimd/server ----> utilisé sur le [Comptoir du Libre](https://comptoir-du-libre.org/fr/softwares/362)

et une partie de l'histoire du fork : https://github.com/codimd/server/blob/master/docs/history.md

en regardant la modification plus précisément :
```diff
-180,CodiMD, (...),En version 1.4.1 à la DINUM,MIMO,
+180,CodiMD, (...),En version 1.6.1 à la DINUM,MIMO,
```

et en comparant avec les différentes releases sur les 2 dépôts :
- [hackmdio/codimd](https://github.com/hackmdio/codimd/tags)
  - 2.0.1
  - 2.0.0
  - 1.4.1 
  -  1.4.0
  - 1.3.1  ---> dernier commit  `50c80c9` commun
  -  ...
- [codimd/server](https://github.com/codimd/server/tags)
  - 1.6.0
  - 1.5.0
  -  1.4.0
  - 1.3.2
  - 1.3.1  ---> dernier commit  `50c80c9` commun
  -  ...

plusieurs  constatations :
- pas de version 1.6.1 sur aucun des 2 dépôts ---> version 1.6.0 sur [codimd/server](https://github.com/codimd/server/tags) uniquement
- la version 1.4.1 précédemment déclarée comme utilisée "En version 1.4.1 à la DINUM" est sur le dépôt [hackmdio/codimd](https://github.com/hackmdio/codimd/tags)
- la version 1.6.x actuellement déclarée comme utilisée "En version 1.6.1 à la DINUM" est sur le dépôt [codimd/server](https://github.com/codimd/server/tags)

Donc questions :
- quelle est la version actuellement utilisée  à la DINUM ?
- à partir de quels dépôts **hackmdio/codimd** ou **codimd/server** ? (la 1ᵉʳ question permet de répondre logiquement à cette question).

**Comment by bzg** [comment]
Merci d'avoir remonté ce problème. La version minimale recommandée par la DINUM est la 1.4.1 pour l'instant, et la DINUM utilise `hackmdio/codimd`.

A noter qu'un autre utilisateur de `codimd` dans l'administration a été contacté et pourrait devenir le référent SILL sur ce logiciel, du coup ça évoluera peut-être.

**Comment by dzc34** [comment]
Merci pour les précisions.
Pas simple les forks avec les noms identiques.

Les URLs sur la [fiche **CodiMD** du Comptoir-du-Libre](https://comptoir-du-libre.org/softwares/362) ont été modifiées pour prendre en compte la version et le dépôt actuellement préconisés dans le SILL.

**Comment by bzg** [comment]
> Les URLs sur la fiche CodiMD du Comptoir-du-Libre ont été modifiées pour prendre en compte la version et le dépôt actuellement préconisés dans le SILL.

Super, merci pour ça !
