### ISSUE TITLE
Proposition d'aide : X

### ISSUE THREAD

**Issue by Pbast** [DISIC/sill#108]
Bonjour,

Ministère de la Transition écologique et solidaire/SG/MSP/DAM/SNUM

Je souhaite  proposer un logiciel en vue du SILL 2020: XWiki (https://www.xwiki.org/)  une application sous license Creative Common 1.0
De même, je souhaite être referents pour cette application web XWiki que j'ai mise en place dans notre ministère (maitrise d'oeuvre). J'ai contribué au développement open source et à la documentation avec la communauté d'XWiki.

Notre site IWiki (moteur XWiki) est principalement utilisé par les agents d'Administration Centrale pour partager les retour d'expérience des chefs de projets des SI et à des fins de capitalisation (démarche qualité).
Le site est accessible sur notre intranet et internet (soumis à une authentification)

Merci.
Pascal

**Comment by bzg** [comment]
Bonjour, vous avez ouvert une issue vide : quelle était la demande ?

**Comment by Pbast** [comment]
Oui désolé j'ai ouvert cette demande pour proposer XWiki et en être le référents. J'ai raccroché la touche d'envoi :/
Je viens d'éditer la demande original

**Comment by bzg** [comment]
Merci pour la proposition !

C'est donc une instance du logiciel xwiki déployée sur des serveurs que vous gérez ?  Le SILL ne contient que des _logiciels_ (pas des services), la condition étant que le référent puisse aider les autres référents s'ils veulent _installer_ le logiciel sur leurs infrastructures (même si les autres référents ne dépendent évidemment pas de lui techniquement.)

Merci d'avance pour la précision !

**Comment by Pbast** [comment]
XWiki n'est pas du Saas. C'est une application web qui a besoin d'un serveur java+SGBD, tel que tomcat/postgresql pour fonctionner.
Je l'ai installée/paramètré sur un de nos serveur debian (sur un hébergement sec càd un linux nu +SSH est fournis) et j'en assure le MCO/upgrade de versions.
Je peux très bien aider les autres référents à l'utiliser/installer/tester comme je le fais pour la communautés xwiki sur leur forum ou directement sur xwiki.org (c'est un wiki)

A noter que XWiki permet facilement de créer une ferme de wiki (par ex. pour fournir des sous-wiki en tant que service) mais j'ai juste mis à dispo un wiki principal qui est bien suffisant pour l'administration centrale.

A votre dispos pour plus de détails

**Comment by bzg** [comment]
Parfait, merci pour la confirmation ! Pouvez-vous m'envoyer un mail à `bastien.guerry @ data.gouv.fr` pour la suite ?

**Comment by Pbast** [comment]
Oui avec mon mail en gouv.fr (je termine une réunion/visio)

**Comment by bzg** [comment]
XWiki est dans le sill: https://sill.etalab.gouv.fr/fr/software?id=214
