### ISSUE TITLE
Consul : incohérence des liens

### ISSUE THREAD

**Issue by sguerlet** [DISIC/sill#109]
Bonjour,

L'entrée ["Consul"](https://sill.etalab.gouv.fr/en/software?id=26) du SILL est incohérente en terme de lien/logo :
- les liens du site web et du code source pointent vers la solution Consul d'Hashicorp (configuration distribuée)
- le lien "Comptoir du libre" et le logo de la fiche font référence à la solution de débat citoyen/vote Consul  http://consulproject.org/

**Comment by bzg** [comment]
Merci pour votre message, ce point nous a déjà été signalé par ailleurs, nous sommes en train de voir comment le résoudre - je laisse ouvert en attendant.

**Comment by dzc34** [comment]
URL complémentaires :
- [sill-2020.csv ligne L27](https://github.com/DISIC/sill/blob/master/2020/sill-2020.csv#L27)
- [wikiData Q28709844](https://www.wikidata.org/wiki/Q28709844) 
- [Consult (solution de débat) sur le "Comptoir du libre"](https://comptoir-du-libre.org/en/softwares/317)

**Comment by bzg** [comment]
C'est corrigé en partie.  Le logo affiché vient du cache de Wikidata qui n'a pas intégré la suppression de cette référence, ce sera corrigé je pense d'ici demain. Ne pas hésiter à rouvrir cette issue si ce n'est pas le cas.
