### ISSUE TITLE
Nouveau logiciel : Pentaho

### ISSUE THREAD

**Issue by v20100v** [DISIC/sill#111]
### Pentaho 

Il s'agit d'une solution d'informatique décisionnelle (plateform BI) précédemment inscrite au SILL édition 2017. Cette solution est constitué de différents composants dont : 

- Pentaho Data Integration (aka Kettle) : solution ETL pour l'intégration des données
- Pentaho Server (aka Business Analytics platform)
- et bien d'autres composants et extensions dont on peut voir la liste ici : https://en.wikipedia.org/wiki/Pentaho

### Ressources URLs
- https://community.hitachivantara.com/s/pentaho
- https://community.hitachivantara.com/s/article/downloads
- https://community.hitachivantara.com/s/article/data-integration-kettle
- https://www.osbi.fr/decouvrir-pentaho/

### Pentaho licenses : entreprise edition and community edition
Pentaho follows an open core business model. It provides two different editions of Pentaho Business Analytics: a community edition and an enterprise edition. 

The enterprise edition needs to be purchased on a subscription model. The subscription model includes support, services, and product enhancements via annual subscription.[23] The enterprise edition is available under a commercial license. Enterprise license goes with 3 levels of Pentaho Enterprise Support: Enterprise, Premium and Standard. 

The community edition is a free open source product licensed under the GNU General Public License version 2.0 (GPLv2), GNU Lesser General Public License version 2.0 (LGPLv2), and Mozilla Public License 1.1 (MPL 1.1).

### Identification référent

| Nom  | Fonction | Structure |
|---|---|---|
|  Yannick LE-PON  | Développeur full-stack, ingénieur de données | Académie Orléans-Tours / Division de l'évaluation et de la prospective / Pôle analyse et développement informatique
|  Vincent BLAIN | Chef de projet informatique - Ingénierie logicielle |  Académie Orléans-Tours / Division de l'évaluation et de la prospective / Pôle analyse et développement informatique

Contact : padi@ac-orleans-tours.fr

**Comment by bzg** [comment]
Pentaho CE est désormais dans le SILL : https://sill.etalab.gouv.fr/fr/software?id=212
