### ISSUE TITLE
Nouveau logiciel : Composer

### ISSUE THREAD

**Issue by v20100v** [DISIC/sill#112]
### Composer

Outil de gestion des dépendances PHP
https://getcomposer.org/

### Licence

Composer and all content on this site are released under the MIT license.

### Référent pour porter ce logiciel ? 
N'importe quel développeur PHP

**Comment by bzg** [comment]
Les propositions d'ajout dans le SILL vont être gérées autrement à partir de 2022.  Nous avons bien noté celle-ci.
