### ISSUE TITLE
Nouveau logiciel : Symfony

### ISSUE THREAD

**Issue by v20100v** [DISIC/sill#113]
### Symfony framework

Framework de développement PHP et ensemble de composants réutilisables.

### URL
- https://symfony.com/what-is-symfony
- https://symfony.com/components

### Symfony licences
Symfony code is released under the MIT license:

The Symfony documentation is licensed under a Creative Commons Attribution-Share Alike 3.0 Unported License (CC BY-SA 3.0).
https://symfony.com/doc/current/contributing/documentation/license.html

###  Référent pour porter ce logiciel ?
De nombreuses académies du MEN ont des cellules/pôle de développement qui utilisent ce framework pour la conception d'applications locales.

**Comment by bzg** [comment]
Les propositions d'ajout dans le SILL vont être gérées autrement à partir de 2022.  Nous avons bien noté celle-ci.
