### ISSUE TITLE
Nouveau logiciel : Iptables / Netfilter

### ISSUE THREAD

**Issue by ZerooCool** [DISIC/sill#114]
https://www.netfilter.org
https://www.netfilter.org/news.html#2019-05-27b
https://www.netfilter.org/about.html#license

Non, pas de porteur identifié dans l'administration.

J'ai envoyé un mail pour proposer Iptables / Netfilter, voilà la réponse reçue :

```
merci pour votre message.

Je vous invite à lire https://sill.etalab.gouv.fr/fr/about et
https://disic.github.io/sill/ qui expliquent ce qui fait qu'un
logiciel est référencé au SILL ou non.

Il est certain que Iptables est utilisé dans l'administration : mais
soit c'est trop "bas niveau" pour nécessiter un référencement, soit il
n'y a pas eu d'agent public pour être référent SILL volontaire.

Si vous connaissez des logiciels libres dont vous savez qu'ils sont
utilisés dans l'administration et connaissez aussi un agent public
qui serait motivé pour être référent SILL, n'hésitez pas à lui dire
de ce manifester.

N'hésitez pas en attendant à proposer ces logiciels ici :
https://github.com/disic/sill
```

Mes recherches sur IPtables : 
https://wiki.visionduweb.fr/index.php?title=Configurer_le_pare-feu_Iptables

**Comment by bzg** [comment]
Les propositions d'ajout dans le SILL vont être gérées autrement à partir de 2022.  Nous avons bien noté celle-ci.
