### ISSUE TITLE
Nouveau logiciel : LinShare dans les solutions de partage de fichiers

### ISSUE THREAD

**Issue by pvi-github** [DISIC/sill#115]
Bonjour,
Je crée ma première issue ici pour l'ajout de LinShare au SILL.

### Nom
LinShare

### urls
site web : https://www.linshare.org/

forge : https://github.com/linagora/linshare

License : https://www.linshare.org/files/LinShare-License_AfferoGPL-v3_en.pdf

### Fonctionnalites

LinShare est un logiciel de **partage de fichiers** libre (Licence AGPL poussée par la Free Software Foundation).

- Il permet de déposer des fichiers dans un espace personnel en ligne et de les partager à partir de cet espace.
- Le partage peut se faire à destination d'utilisateurs tiers (un peu comme Wetransfer™ sauf que le serveur il est sous votre contrôle au lieu de celui de Wetransfer™ ou Dropbox™ ou Google™)
- Le partage peut se faire aussi au sein de groupes de travail.
- Des délais de péremption peuvent être définis
- Il est possible  de gérer (créer ou supprimer) des groupes ou listes de diffusion.
- La traçabilité des partages ou des téléchargements est possible grâce à un mécanisme de suivi d'historique.
- Des notifications par mail peuvent être envoyées lors d'événements tels que des téléchargements ou des expirations de délais.
- Les fichiers peuvent être chiffrés et protégés par mot de passe.
- Le design responsive des interfaces permet de l'utiliser sur diverses tailles d'écrans jusqu'aux tablettes et aux téléphones.
- Une application mobile permet de gérer ses fichiers et ses partages en mouvement (A partir de la version 2.3 du serveur).

### Utilisations connues dans l'Administration
- Ministère des Finances
- Ministère de l'Intérieur
- Ministère de la Culture
- Cour des Comptes
- Direction Générale de l'Aviation Civile

### Referent(s)
Sophie MALON, Ministère des finances, SG/SEP1B

Merci d'avance pour la prise en compte de cette soumission (et aussi pour vos retours, ça me permettra d'améliorer mes prochaines issues si jamais).

Très cordialement,

**Comment by bzg** [comment]
Bonjour et merci pour cette proposition.  Si Mme Malon est bien volontaire pour être référente de LinShare, pouvez-vous lui demander de me contacter par mail ? `bastien.guerry@data.gouv.fr`

Merci !

**Comment by pvi-github** [comment]
Bonjour,

C'est fait, elle vous a envoyé un email dans la journée.

Très cordialement,

**Comment by bzg** [comment]
Bonjour, j'ai répondu à Mme Malon hier, elle peut désormais proposer LinShare au référencement. Merci !

**Comment by bzg** [comment]
Bonjour, sauf erreur de ma part, la licence sur le dépôt https://github.com/linagora/linshare n'est pas indiquée.

J'ai ouvert [cette issue](https://github.com/linagora/linshare/issues/120) pour suivre l'ajout, qui est un prérequis pour que le logiciel soit référencé au SILL.

**Comment by pvi-github** [comment]
Bonjour,

Les fichiers de licence sont arrivés dans les dépots github de LinShare.

J'ai commenté l'issue que vous avez ouvert  [/linagora/linshare/issues/120](/linagora/linshare/issues/120) et je fais le pendant ici pour la bonne forme.

Reste-t-il quelque chose à faire pour aider au référencement de LinShare ?

Très cordialement,
PVI

**Comment by bzg** [comment]
Merci pour les ajouts !  Il y a une URL à corriger dans `COPYING.md` et ensuite on devrait être bon, mais je souhaite lire le contenu pointé par cette URL justement.

**Comment by pvi-github** [comment]
Rebonjour,

L'URL devrait pointer vers les fichiers qui sont là : http://download.linshare.org/licence/ (C'est le même sous deux formats : pdf et markdown)

Le fichier dont l'URL est "cassée" (LinShare-License_AfferoGPL-v3.pdf) semble avoir été déplacé dans le sous-répertoire "old"

En espérant que ça aide.

Très cordialement,
PVI

**Comment by bzg** [comment]
Bonjour, pardon je n'ai peut-être pas été assez clair.

Le fichier [COPYING.md](https://github.com/linagora/linshare/blob/master/COPYING.md) contient un lien vers une URL `http://www.linshare.org/licenses/LinShare-License_AfferoGPL-v3.pdf` qui fait arriver sur cette page d'erreur:

![2020-07-08-104202_1920x1080_scrot](https://user-images.githubusercontent.com/63500/86897564-de7eb880-c107-11ea-82bf-bcec8654afae.png)

Il faudrait corriger ce lien pour que les instructions de `COPYING.md` soient correctes.

**Comment by pvi-github** [comment]
Rebonjour,

Si, si, vous avez été parfaitement clair (moi un peu moins visiblement) et j'ai déjà fait passer l'info pour que ça soit corrigé (Merci pour votre vigilance au passage).

En fait comme vous sembliez vouloir lire le document je vous ai en parallèle donné le "bon" emplacement afin de vous faciliter la vie.

Très cordialement,
PVI

**Comment by bzg** [comment]
OK, merci. J'ai lu le document `LinShare-License-AfferoGPL_V3_7bce_terms.pdf` et je vais consulter en interne pour vérifier que les demandes supplémentaires faites par rapport à une licence Affero GPL permettent de continuer à qualifier la licence de "FSF approved", un prérequis pour l'ajout au SILL.

Si vous avez des éléments à apporter pour cette question, n'hésitez pas.

**Comment by pvi-github** [comment]
Bonjour,

Les liens morts ont tous été corrigés. Merci pour vos retours ça fait déjà plus propre que des 404.

La démarche de vérification est super intéressante, je suis curieux des résultats que ça donnera. S'il y a des remarques à prendre en compte je transmettrai, ça sera peut être une nouvelle occasion d'améliorer les choses.

Bon week-end,
PVI
