### ISSUE TITLE
Amélioration : changement de l'url pour les sources de LemonLDAP::NG

### ISSUE THREAD

**Issue by bilbo-the-hobbit** [DISIC/sill#116]
les sources pour LemonLDAP::NG pointent vers un depot svn qui n'existe plus

le projet est heberge sur le gitlab de ow2.org

https://gitlab.ow2.org/lemonldap-ng/lemonldap-ng

corrige un erreur sur la fiche de LemonLDAP::NG

**Comment by bzg** [comment]
Merci ! 

Le dépôt de code source indiqué dans le SILL est collecté depuis l'entité wikidata, quand celle-ci est connue.

J'ai donc mis à jour l'entité de [LemonLDAP::NG](https://www.wikidata.org/wiki/Q3229380) pour ajouter ce dépôt, avec la date d'aujourd'hui comme date de consultation.

Il y a actuellement un bug qui fait que les données collectées ne retiennent que le premier dépôt indiqué sur l'entité Wikidata, et non celui contenant la date de consultation ou la référence la plus récente.  Je dois corriger cela pour que l'erreur disparaisse de sill.etalab.gouv.fr, je pense faire ça d'ici la semaine prochaine.

**Comment by bzg** [comment]
C'est corrigé - merci !
