### ISSUE TITLE
Color Contrast Analyser : URLs ?

### ISSUE THREAD

**Issue by dzc34** [DISIC/sill#118]
Quels sont les URLs du logiciel "Color Contrast Analyser" ?
https://sill.etalab.gouv.fr/fr/software?id=204

C'est ce logiciel : "Colour Contrast Analyser (CCA)" de paciellogroup ?
- https://developer.paciellogroup.com/resources/contrastanalyser/
- https://github.com/ThePacielloGroup/CCAe

**Comment by bzg** [comment]
> Quels sont les URLs du logiciel "Color Contrast Analyser" ?
> https://sill.etalab.gouv.fr/fr/software?id=204
>
> C'est ce logiciel : "Color Contrast Analyser (CCA)" de paciellogroup ?

Oui (avec "Colour" plutôt que "color"):

- https://developer.paciellogroup.com/resources/contrastanalyser/
- https://github.com/ThePacielloGroup/CCA-Win (version historique)
- https://github.com/ThePacielloGroup/CCAe (nouvelle version, sur base Electron)
