### ISSUE TITLE
Cas d'usage : 

### ISSUE THREAD

**Issue by jyterrien** [DISIC/sill#125]
Bonjour

Je suis en charge du choix des outils pour le service développement d'application pour les Hôpitaux de Paris.
Je ne sais pas trop ni où ni comment ouvrir une discussion sur les forges logicielles.

1) le sill n'est pas (encore) ouvert aux établissements. Je peux affirmer qu'il n'en est pas moins consulté. et c'est une attente.
2) le sill contient divers outils qui couvrent les besoin d'une équipe de développement. Mais il n'est pas abordé les forges.
utiliser un dépos de sources + un tracker + un... + un... demande d'administrer séparément ces divers outils et de maintenir leur liaison. Et il est alors nécessaire de le faire projet par projet.

Forges logicielles : Tuleap, gForge, redmine, gitlab etc.
Centralisation de tous les projet de l'établissement: un serveur pour tous
Gestion unique des utilisateur/rôles pour tous les services de tous les projets
Gestion des sources
Gestion des évolutions/anomalies
Support des méthodes agiles et/ou cycle en V
Gestions de la documentations interne (équipe de dev)
Publication documentation du projet (communication externe)
Gestion des Tests
Outils de communication équipe de Dev (forum/chat/mailinglist etc)
Interaction avec les outils CI/DevOps (jenkins/hudson ...)
Suivi de la qualité
Repporting (par projet mais aussi pour l'ensemble des projet)

généralement les forges offrent aussi le dépôt des livrable qui aujourd'hui est plutôt délégué à nexus

Toutes

Impossible de partager le serveur est sur un réseau privé
tuleap.aphp.fr

**Comment by bzg** [comment]
Bonjour Jean-Yves,

merci pour ces questions !

> Je ne sais pas trop ni où ni comment ouvrir une discussion sur les forges logicielles.

C'est le bon endroit.

> 1. le sill n'est pas (encore) ouvert aux établissements. Je peux affirmer qu'il n'en est pas moins consulté. et c'est une attente.

À noter que depuis 2020, le SILL s'adresse explicitement à "la fonction publique d'État ou hospitalière" (cf. [cette page](https://sill.etalab.gouv.fr/fr/about)).

> 2. le sill contient divers outils qui couvrent les besoin d'une équipe de développement. Mais il n'est pas abordé les forges.

GitLab et Redmine sont tous deux recommandés dans le SILL : 

https://sill.etalab.gouv.fr/fr/software?id=53

https://sill.etalab.gouv.fr/fr/software?id=122

>     utiliser un dépos de sources + un tracker + un... + un... demande d'administrer séparément ces divers outils et de maintenir leur liaison. Et il est alors nécessaire de le faire projet par projet.

Oui, le SILL ne permet pas encore de répondre à cette problématique de mise en cohérence des applications, qui est commune à de nombreux établissements.  Pour cela, nous envisageons de publier des cas d'usage, lesquels pourront donner des exemples de solutions à cette problématique -- il y a peu de chances pour qu'il y ait une solution unique.

Si vous avez besoin d'aide de la communauté, n'hésitez pas à envoyer un mail à mim-devops@listes.etalab.gouv.fr

Bonne journée !

**Comment by bzg** [comment]
Bonjour, pour information, un atelier autour de Tuleap est prévu le 15 janvier à 11h, voir les détails sur [le calendrier des événements #BlueHats](https://pad.incubateur.net/d3cj0U1WT42y-rQoozp4gQ).

**Comment by jyterrien** [comment]
Bonsoir

Nous utilisons Tuleap pour une 50 de projet et 130 personnes

Je peux faire un petit retour d'expérience si ça vous dit

A+JYT

**Comment by bzg** [comment]
Merci ! J'ai signalé cette proposition aux intervenants du 15 janvier.
