### ISSUE TITLE
Nouveau logiciel : Tuleap

### ISSUE THREAD

**Issue by bzg** [DISIC/sill#126]
- Tuleap
- https://www.tuleap.org/fr/
- https://github.com/Enalean/tuleap (GPL-2.0)

Tuleap est utilisé par le programme VITAM, le MinArm et l'APHP (cf. [cette issue](https://github.com/DISIC/sill/issues/125)).

**Comment by jeffix2000** [comment]
# Emploi au MinArm

Tuleap est une application web collaborative de gestion de projet ou produit. Utilisé à son plein potentiel comme application lifecycle management (ALM, gestion de cycle de vie d'applications), la polyvalence de ses fonctions et l'adaptabilité de son modèle de données lui permettent d'outiller de nombreux contextes de pilotage d'activité.

## Tuleap, pourquoi faire ?

**Gagner du temps & fiabiliser l’info. en centralisant les données de l’équipe et en organisant son travail**

**_Trackers_** = suivi collaboratif (dans une appli web sur l'intranet)...
...  de « choses » ou objets métier : actions, objectifs, incréments, demandes, faits techniques, moyens, etc.,
... caractérisées par des données structurées ⇒ champs, relations, règles…
...  complètement adaptables par le gestionnaire d’un espace à son cas d’usage.

Tuleap fournit nativement, sur ces données :
- de quoi organiser votre équipe :
- historisation, commentaires, attribution, notifications, workflow sur états, permissions
- des rapports tableaux & graphiques simples
- des interfaces de planification

et en outre, dans un usage développement logiciel ou simulation :
- gestion de configuration de sources
- revue de contributions
- suivi des tests
- distribution de paquets.

## Cas d'usage typiques

### Suivi d'actions en équipe - gestion de projet

Tracker(s), indicateurs graphiques, Kanban interactif...
Remplace avantageusement les tableaux bureautiques de suivi et leurs extraits pour des comités : l'information peut être saisie et consultée en temps réel par les acteurs concernés. On peut maîtriser les permissions par ligne et/ou par champ.

![image](https://user-images.githubusercontent.com/43076120/105340444-2c5b9980-5bde-11eb-96d4-070741c4fd86.png)

### Faciliter l'introduction de l'agilité d'entreprise

Les interfaces et les modes de travail collaboratifs permis par un tel outil encouragent la transition vers le Lean, le management visuel, la planification de portefeuille agile (estimation de valeur et d'effort et gestion des files d'attentes au lieu d'une planification fragile par échéances et imputations - voir [un article](https://www.linkedin.com/feed/update/urn:li:activity:6664910766354776064/) que j'ai publié sur ce sujet "métier").

![image](https://user-images.githubusercontent.com/43076120/105340402-1f3eaa80-5bde-11eb-89aa-93856a85bb54.png)

### Piloter le traitement de demandes ou de problèmes

Dialogue entre demandeur, pilote et contributeurs dans le cadre d'une mission de service.
Captation des problèmes/rétrospectives pour l'amélioration continue d'un processus, de faits techniques pour le maintien en conditions opérationnelles d'un produit, de bugs pour un logiciel évidemment...

![image](https://user-images.githubusercontent.com/43076120/105340381-177f0600-5bde-11eb-9f20-d94ece27fe77.png)


### Workflows simples de gestion

Maîtrise de la séquence de traitement d'un objet métier (représenté par un tracker largement personnalisé, donc) au moyen :
- de groupes d'utilisateurs représentant des rôles,
- des permissions sur les artefacts (qui voit quels objets) et sur les champs (qui voit et saisit quels attributs)
- de la définition d'états successifs (représentation Kanban possible)
- de la configuration des transitions entre ces états : on peut passer de quelle phase à quelle autre, qui peut le faire, champs requis à ce stade, mise d'un champ numérique ou date à une valeur donnée (ou déclenchement d'un webhook pour les plus avancés) en sortie d'opération.

![image](https://user-images.githubusercontent.com/43076120/105340357-0fbf6180-5bde-11eb-9690-4e6eef59f624.png)

### Gérer de bout-en-bout un produit numérique (logiciel, modèle)

Suivi des besoins et problèmes > Gestion de configuration de code > Déclenchement de tests d'intégration > Remontée des résultats et Revue des modifications > Déploiement après intégration > autres tests > Utilisation ...

![image](https://user-images.githubusercontent.com/43076120/105340688-82304180-5bde-11eb-98a1-48917f499108.png)


## Différenciateurs principaux

Organisation riche :  un espace de collaboration (équipe produit etc.) peut comporter plusieurs trackers (classes d'objets à suivre) articulés entre eux.

Polyalence : la fonction _tracker_ est en fait un méta-modèle de données et de fonctions de travail autour de ces données.

Open-source : favorise l'intégration (et protège la capacité à sortir) par des formats ouverts ; facilite l'expérimentation avant investissement en support et quelques plugins Entreprise (seuls ceux-ci ne sont pas librement redistribuables).

Crédits illustrations : Enalean.
Présentation du logiciel : https://www.tuleap.org
Instance de gestion du produit : https://tuleap.net/projects/tuleap

**Comment by dzc34** [comment]
ID comptoir du libre : **325**
https://comptoir-du-libre.org/fr/softwares/325

**Comment by bzg** [comment]
Merci pour la proposition, c'est en cours d'évaluation.
