### ISSUE TITLE
Nouveau logiciel : uPortal

### ISSUE THREAD

**Issue by jgribonvald** [DISIC/sill#128]
uPortal

site de la fondation (non lucrative) portant le projet: https://www.apereo.org/projects/uportal
sources: https://github.com/Jasig/uPortal 
licence Apache 2 indiquée dans les sources du projet

Référent: Moi même, l'un des rares commiter Français sur le projet, je suis aussi membre du groupe communautaire de "direction" du projet.

Cas d'usage: Ce portail est utilisé comme base de la solution ENT en région Centre-Val de Loire, du collège jusqu'à l'université. C'est une solution assez répandue et qui est déployée dans l'éducation au niveau international, principalement dans les universités (consortium ESUP-Portail en France).

**Comment by bzg** [comment]
Bonjour, merci pour cette proposition.

Le SILL ne référence pas les solutions de la fonction publique territoriale, dont relèvent les collectivités.  Il faudrait un usage dans une université ou un centre de recherche.  Les référents SILL doivent par ailleurs être des agents publics. Pouvez-vous m'indiquer par mail (bastien.guerry@data.gouv.fr) si (1) vous êtes agent public (ou connaissez un agent qui pourra être référent) et (2) s'il y a des instances dans la fonction publique d'Etat, idéalement dans le service pour lequel vous travaillez ?

Merci beaucoup !
