### ISSUE TITLE
Nouveau logiciel : PeerTube

### ISSUE THREAD

**Issue by XanderLeaDaren** [DISIC/sill#129]
### PeerTube

Site : https://joinpeertube.org/

GitHub : https://github.com/Chocobozzz/PeerTube

Licence : GNU Affero General Public License v3.0

### Référents :
Une page de descriptif https://lyceeconnecte.fr/peertube et ses partenaires clairement identifiables :
* https://www.nouvelle-aquitaine.fr/
* http://www.ac-poitiers.fr/
* http://www.ac-limoges.fr/
* http://www.ac-bordeaux.fr/
* https://www.educagri.fr/

**Comment by bzg** [comment]
Bonjour @XanderLeaDaren et merci pour la proposition !

Peertube est déjà référencé dans le SILL: https://sill.etalab.gouv.fr/fr/software?id=197
