### ISSUE TITLE
Ajout de JobScheduler

### ISSUE THREAD

**Issue by bzg** [DISIC/sill#13]
https://fr.wikipedia.org/wiki/JobScheduler

**Comment by PenoKrish** [comment]
Bonjour,

Je suis expert sur la solution JobScheduler.
J'ai mis en place pour le groupe Societe Generale afin de réduire les coûts  et de concurrencer l'ordonnanceur Control-M. 
D'ici fin 2019, j'ai prévu 15000 jobs sur cet outil.
Je suis à votre disposition pour toutes questions.

Cordialement,

**Comment by PenoKrish** [comment]
http://www.sos-berlin.com/jobscheduler

**Comment by bzg** [comment]
Merci. Les suggestions faites dans les issues de ce dépôt sont en attente de choix stratégiques pour un repositionnement du SILL, mais elle seront bien prises en compte.

**Comment by bzg** [comment]
Les propositions d'ajout dans le SILL vont être gérées autrement à partir de 2022.  Nous avons bien noté celle-ci.
