### ISSUE TITLE
Amélioration : remplacer CodiMD par HedgeDoc

### ISSUE THREAD

**Issue by bzg** [DISIC/sill#132]
Le référent pour CodiMD (DINUM) utilise désormais [HedgeDoc](https://hedgedoc.org/history/), il faudrait mettre le SILL à jour en conséquence.

**Comment by dzc34** [comment]
L'ID comptoir pour _HedgeDoc_ : **422**
https://comptoir-du-libre.org/fr/softwares/422

L'ID comptoir pour _CodiMD_ n'a pas changé.
