### ISSUE TITLE
Proposition d'aide : 

### ISSUE THREAD

**Issue by MAG-33** [DISIC/sill#135]
Bonjour, 

Je suis fonctionnaire (CNRS)
Je souhaiterais ^etre référent pour  : 

Lazarus/freepascal : https://www.lazarus-ide.org/
PilotLogic : https://www.pilotlogic.com/sitejoom/

Afin de les rajouter à la liste du SILL

Cordialement.

Michel GONZALEZ

**Comment by bzg** [comment]
Bonjour et merci pour votre proposition.

Pouvez-vous donner quelques informations supplémentaire pour chaque logiciel:

- quel usage en est fait dans votre administration (et d'autres éventuellement) ?
- quelle est la licence libre ?
- existe-t-il une entité [Wikidata](https://www.wikidata.org/) ?

Merci d'avance pour les précisions !

**Comment by MAG-33** [comment]
J’utilise ces logiciels (lazarus et CodeTyphon) pour divers petites applications à usage interne et multi-plateforme.

Les outils que j’ai dévellopé permettent une meilleure ergonomie et un gain de temps appréciables pour les utilisateurs.

En interaction constante avec les services et disposant des sources, je peux dès que cela est nécessaire intervenir et assurer une maintenance évolutive et curative de ces développements.


________________________________
De : Bastien ***@***.***
Envoyé : jeudi 1 avril 2021 11:08
À : DISIC/sill
Cc : GONZALEZ Michel; Author
Objet : Re: [DISIC/sill] Proposition d'aide : (#135)


Bonjour et merci pour votre proposition.

Pouvez-vous donner quelques informations supplémentaire pour chaque logiciel:

  *   quel usage en est fait dans votre administration (et d'autres éventuellement) ?
  *   quelle est la licence libre ?
  *   existe-t-il une entité Wikidata<https://www.wikidata.org/> ?

Merci d'avance pour les précisions !

**Comment by bzg** [comment]
Bonjour, merci pour votre retour.  Pouvez-vous m'indiquer les licences sous lesquels ces logiciels sont distribués ainsi que la version minimale que vous recommanderiez à l'administration ?  C'est pour préparer l'email que vous enverrez aux autres référents SILL qui évalueront l'intérêt d'intégrer ces logiciels au socle.  Merci !

**Comment by MAG-33** [comment]
Les licences sont :

Pour lazarus : Licence LGPL/GPL
https://wiki.lazarus.freepascal.org/licensing#Licensing_relating_to_FPC.2FLazarus_usage

et LGPL pour le compilateur Freepascal
https://www.freepascal.org/

Pour CodeTyphon : Freeware/Open source pour l’EDI
http://www.pilotlogic.com/codetyphon/license.htm

et LGPL pour le compilateur Freepascal (idem pour Lazarus)
https://www.freepascal.org/

----------------------------------------------
Les versions minimales a recommander pour l'administration :

Pour Lazarus : La dernière en date « Lazarus 2.0.12 »
https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%202.0.12/
Compilateur FPC version 3.2.0

Pour CodeTyphon : La dernière en date 7.30

https://www.pilotlogic.com/sitejoom/index.php/downloads/download/14-codetyphon/123-codetyphonins-zip.html

Compilateur FPC version 3.2.0


Cordialement.


________________________________
De : Bastien ***@***.***
Envoyé : jeudi 1 avril 2021 12:10
À : DISIC/sill
Cc : GONZALEZ Michel; Author
Objet : Re: [DISIC/sill] Proposition d'aide : (#135)


Bonjour, merci pour votre retour. Pouvez-vous m'indiquer les licences sous lesquels ces logiciels sont distribués ainsi que la version minimale que vous recommanderiez à l'administration ? C'est pour préparer l'email que vous enverrez aux autres référents SILL qui évalueront l'intérêt d'intégrer ces logiciels au socle. Merci !

**Comment by bzg** [comment]
Merci beaucoup.  

Pour codetyphon, la licence ne fait malheureusement pas partie des licences libres permettant à un logiciel de rejoindre le SILL.  Voir [cette page](https://disic.github.io/sill/index.html#orgbcdab87).

**Comment by bzg** [comment]
Pouvez-vous m'écrire à `bastien.guerry@data.gouv.fr` pour que je vous envoie les instructions par email pour la suite ?

**Comment by MAG-33** [comment]
Je m'en doutais un peu. CodeTyphon a fait couler un peu "d'encre" sur developpez.com.
Mais je dois reconnaitre que la mise en place de la crosscompilation (multiplateforme) est hyper conviviale ;).
Il nous reste donc Lazarus ;)
________________________________
De : Bastien ***@***.***
Envoyé : jeudi 1 avril 2021 14:46
À : DISIC/sill
Cc : GONZALEZ Michel; Author
Objet : Re: [DISIC/sill] Proposition d'aide : (#135)


Merci beaucoup.

Pour codetyphon, la licence ne fait malheureusement pas partie des licences libres permettant à un logiciel de rejoindre le SILL. Voir cette page<https://disic.github.io/sill/index.html#orgbcdab87>.

**Comment by bzg** [comment]
C'est désormais publié, merci beaucoup !

**Comment by MAG-33** [comment]
Bonjour,


Merci surtout au SILL.

Je dois avouer qu‘il m’est agréable de voir que le logiciel que j’utilise depuis des décennies soit référencé alors qu’il est bien moins populaire que d’autres. Il faut espérer que ce référencement contribue a sont maintiens parmi les AGL et qu’il donne naissance à d’autres logiciels opensource.


Michel

________________________________
De : Bastien ***@***.***
Envoyé : mercredi 14 avril 2021 12:01
À : DISIC/sill
Cc : GONZALEZ Michel; Author
Objet : Re: [DISIC/sill] Proposition d'aide : (#135)


C'est désormais publié, merci beaucoup !

**Comment by dzc34** [comment]
Bonjour,

Les fiches sur Comptoir du Libre ont été ajoutées pour :
- Lazarus IDE - https://comptoir-du-libre.org/fr/softwares/430
- FreePascal - https://comptoir-du-libre.org/fr/softwares/429

@bzg une PR arrive pour mettre à jour le fichier SILL avec les ID du comptoir

@MAG-33 En vous inscrivant sur le Comptoir, vous pouvez modifier ces fiches FreePascal  et Lazarus IDE pour les améliorer, et aussi   vous déclarer comme utilisateur.

**Comment by dzc34** [comment]
> @bzg une PR arrive pour mettre à jour le fichier SILL avec les ID du comptoir

La PR est là : https://github.com/DISIC/sill/pull/137
