### ISSUE TITLE
Nouveau logiciel : 

### ISSUE THREAD

**Issue by MAG-33** [DISIC/sill#136]
1) Lazarus

2) CodeTyphon Studio 

1) https://www.lazarus-ide.org/  ( Open Source)
2) https://www.pilotlogic.com/sitejoom/  (Free and Open Source)

Pas encore. Mais je souhaiterais devenir référent.

**Comment by bzg** [comment]
Bonjour, cette issue est en double de https://github.com/DISIC/sill/issues/135, je ferme.
