### ISSUE TITLE
uMap et non "uMap.OpenStreetMap"

### ISSUE THREAD

**Issue by Cybereric** [DISIC/sill#14]
Bonjour,

Dans le SILL 2019 vous parlez de "uMap.OpenStreetMap"

Quelques précisions à ce sujet.

**1/** "uMap.OpenStreetMap" n'existe pas il s'agit en fait d'"**uMap**".

uMap est accessible à l'adresse [[https://umap.openstreetmap.fr](https://umap.openstreetmap.fr)] parce que c'est l'association « OpenStreetMap France » qui l'héberge.

**2/** Vous classez uMap dans la catégorie  "Orchestration et logique métier > moteur SIG > informations géographiques"
Si on se réfère à la définition d'un SIG [[cf Wikipédia](https://fr.wikipedia.org/wiki/Système_d'information_géographique)] je trouve qu'on ne s'y retrouve pas. 

uMap peut être défini comme un **service web** qui permet de créer des **cartes interactives et personnalisées** sur des fonds de carte OpenStreetMap.[[https://openstreetmap.org](https://openstreetmap.org)]
Les cartes sont destinées à être incluses dans un site web (génération d'un code HTML) ou partagées sous la forme d'un lien hypertexte.

Même s'il est possible d'importer des données géographiques sous forme de POIs, traces, polygones pour les afficher sur un fond de carte il n'y a pas de "traitement" des données comme avec QGis par exemple.
Pour créer et visualiser la carte en fait on ne sort pas du navigateur web.

Pour ce qui est de la "logique métier" je ne vois pas trop non plus. Les usages qui peuvent en être fait sont multiples et pas forcément professionnels.

je pense donc qu'Umap serait mieux dans une catégorie comme :

=> "**Espace utilisateur et canal > navigateur web > création de cartes web interactives**"

ou en créant une rubrique "cartographie"

=> "**Espace utilisateur et canal > cartographie > création de cartes web interactives**"

Renseignements complémentaires :

https://wiki.openstreetmap.org/wiki/FR:UMap

https://github.com/umap-project/umap

Cordialement

Eric B

**Comment by bzg** [comment]
Bonjour @Cybereric,

merci pour vos remarques.  Je suis d'accord avec le problème de classification d'**uMap**.

De mon point de vue, le SILL ne devrait pas référencer des services web, seulement des logiciels installables par les « utilisateurs », qui sont en premier lieu les organismes publics.

Il faudrait donc plutôt référencer https://github.com/umap-project/umap - mais il faudrait pour cela qu'il existe effectivement une instance installée dans un ministère et je pense que ce n'est pas le cas.

Ces questions seront abordées prochainement lors d'une réunion avec les acteurs principaux du SILL, où nous tâcherons de le faire évoluer vers plus de pertinence.

Je garde l'issue ouverte jusqu'à ce que nous ayons avancé là-dessus.

Bonne journée !

**Comment by Cybereric** [comment]
Oui mais justement ne serait-il pas quand même intéressant de signaler l'existence de services libres ? 
De cette manière de futurs utilisateurs d'un service mis en place par un organisme public  verraient qu'il existe autre chose que la solution propriétaire "visible". Et pour les plus curieux d'entre eux ils pourraient déjà commencer à s'en servir.
Si les gens ne sont pas informés de l'existence de quelque chose ils n'iront pas voir plus loin.

Connaissez-vous l'excellent annuaire des logiciels libres proposé par la Faculté de l'environnement naturel, architectural et construit (ENAC) au sein de l'École polytechnique fédérale de Lausanne (EPFL) ? 
Voir https://enacit.epfl.ch/logiciel-libre

Ils présentent donc des logiciels et des services libres de manière très claire et complète je trouve.
Voir ci-dessous la légende de leur tableau.

![legende annuaire logiciels libres epfl enacit](https://user-images.githubusercontent.com/7645549/58021365-fe6daa00-7b0a-11e9-9909-4e98059d22b7.png)

**Comment by bzg** [comment]
> Oui mais justement ne serait-il pas quand même intéressant de signaler l'existence de services libres ?

Pourquoi pas, c'est à discuter avec l'ensemble des acteurs qui font le SILL.

Je ne connaissais pas cet annuaire, merci !
