### ISSUE TITLE
Ajout  de Veyon

### ISSUE THREAD

**Issue by R4Xx** [DISIC/sill#18]
Bonjour,

Je viens à vous dans le cadre d'une demande de renseignements afin de pouvoir ajouter un logiciel à la liste du SILL.
En effet, actuellement formateur en police technique et scientifique, j'enseigne fréquemment en utilisant des démonstrations dérivées informatiques. Or je ne dispose pas de logiciel permettant de prendre la main sur les postes de mes apprenants.

Quelle est la démarche qu'il me faut suivre pour que le logiciel libre "VEYON" puisse être ajouté au socle interministériel des logiciels libres?

Cordialement.

**Comment by bzg** [comment]
Bonjour,

une réflexion est engagée pour la refonte du SILL, à la fois pour sa présentation (en ligne) et pour la façon dont un logiciel peut "entrer" dans le SILL. Aujourd'hui, les logiciels (les "souches") listés le sont parce qu'il existe un usage avéré dans une administration centrale et un référent prêt à répondre aux autres administrations de cet usage. Ce référent est connu des autres administrations mais son nom n'est pas public, pour éviter qu'il joue _de facto_ le rôle de "hotline" pour tous les acteurs publics.

Nous communiquerons sur les évolutions prévues et leur implémentation, qui sera sûrement progressive.  Je laisse l'issue ouverte en attendant, pour la garder dans le radar.

Merci,

**Comment by R4Xx** [comment]
Merci d’avoir pris le temps de répondre.

Dans l’attente de la nouvelle refonte, je vous souhaite une e celle te journée.

**Comment by bzg** [comment]
Les propositions d'ajout dans le SILL vont être gérées autrement à partir de 2022.  Nous avons bien noté celle-ci.
