### ISSUE TITLE
Proposition d'inclusion des logiciels Scenari dans la liste SILL

### ISSUE THREAD

**Issue by lalejand** [DISIC/sill#19]
Bonjour,

SCENARI est une suite de solutions logicielles libres qui s'adresse à des utilisateurs-métiers différents, ayant en commun la création, la conception et la modélisation de documents dans des domaines tels que :

- Enseignement - Formation - Ingénierie Pédagogique (https://scenari.software/fr/co/training.xhtml)
- Rédaction de documentation (https://scenari.software/fr/co/tech-communication.xhtml)
- Gestion & création de documents (https://scenari.software/fr/co/management.xhtml)

Plus d'info sur https://scenari.software/fr/

L'univers Scenari compte différents outil pré-existants et dédiés à différents métiers et utilisés par nombre d'universités, entreprises et particuliers. Les principaux sont:

- **Optim**, suite bureautique Wysiwym (What You See Is What You Mean) qui automatise la publication d'un contenu sous trois formes : site web, papier, diaporama ; et facilite la réutilisation de fragments de contenus. https://doc.scenari.software/Optim/fr/
- **Opale**, pour créer des documents pédagogiques pour la formation présentielle, à distance ou mixte. https://doc.scenari.software/Opale/fr/
- **Dokiel**, pour optimiser la conception de manuels utilisateurs, de sites documentaires web de référence et de supports pédagogiques pour les formations présentielles et distancielles. https://doc.scenari.software/Dokiel/fr/
- **Topaze**, pour concevoir des formations en ligne proposant plusieurs parcours (définis selon le niveau, le thème...) se déroulant selon les réponses de l'apprenant. https://doc.scenari.software/Topaze/fr/
- **Canoprof**, édité par le réseau Canopé du Ministère de l'Enseignement, pour concevoir des ressources pédagogiques transmédias pour le primaire et le secondaire, et les publier et partager avec les pairs. https://www.reseau-canope.fr/canoprof.html

Mais il es possible aussi de créer de nouvelles chaînes documentaires pour des besoins particuliers. À titre d'exemple, la création de contenu du portail https://www.service-public.fr/ est réalisée avec les technologies Scenari.

**Comment by bzg** [comment]
Discuté et fait en partie.
