### ISSUE TITLE
Ajout de logiciels pour le traitement de données

### ISSUE THREAD

**Issue by MaelTheuliere** [DISIC/sill#2]
Bonjour,
Merci pour ce guide. Je suis étonné de ne rien voir sur la partie data, compte tenu de la place croissante que prend le libre dans ce domaine dans l'administration. 
Il me semble qu'on pourrait démarrer simplement en rajoutant R et python dans cette partie. Je pense que Etalab aurait surement d'autres suggestions pour affiner tout cela (librairies de dataviz / cartoviz par exemple comme vega, d3js, kepler.js, leaflet...)

**Comment by bzg** [comment]
Bonjour,
merci pour votre retour.  C'est une bonne suggestion, nous pourrons intégrer ces logiciels dans des évolutions futures du SILL.

**Comment by MaelTheuliere** [comment]
Super bon courage pour la suite.

**Comment by bzg** [comment]
Hello, je ferme cette issue : [RStudio](https://sill.etalab.gouv.fr/fr/software?id=182) a été ajouté, mais pour les autres logiciels, ouvrons une issue par proposition. Toujours avec l'impératif de trouver un référent dans l'administration pour le logiciel.

**Comment by babolab** [comment]
Bonjour,
Merci beaucoup pour l'ajout de RStudio. Je n'ai pas trouvé par contre R dans la liste. Est-il possible de l'ajouter?
Bonne journée!

**Comment by bzg** [comment]
Bonjour,

oui, si vous êtes agent public et souhaitez être le référent SILL pour R: https://disic.github.io/sill/index.html#org356ae69

Sinon vous pouvez solliciter un agent public pour qu'il soit référent.

Ensuite, il suffit d'envoyer un email à sill-mainteneurs@listes.etalab.gouv.fr pour faire la proposition avec:

- le nom du logiciel libre
- la licence utilisée
- éventuellement le lien vers sa fiche https://www.wikidata.org
- la version minimale recommandée

N'hésitez pas à ajouter des compléments sur l'usage que vous avez de R.

Merci !
