### ISSUE TITLE
Retravailler les catégories de recommandation

### ISSUE THREAD

**Issue by bzg** [DISIC/sill#20]
Aujourd'hui, le SILL distingue trois niveaux :

1.  les souches libres *recommandées* (`R`)
2.  les souches libres *en observation* (`O`)
3.  les souches libres *en fin de recommandation* (`FR`)

La proposition consiste à proposer ces niveaux :

1.  les souches libres *recommandées* (`R`)
2.  les souches libres *en observation* (`O`)
3.  les souches libres *en usage* (`U`)

Les souches en fin de recommandation ne feraient plus partie du SILL (mais la mise à jour du SILL indiquerait la liste des souches qui en sortent) et les souches *en usage* seraient des logiciels utilisés sans avoir cocher tous les critères pour atteindre le niveau *recommandé*.

**Comment by fanetk** [comment]
Parfait (en ce qui me concerne) et compréhensible si c'est bien traité ainsi.

**Comment by bzg** [comment]
Voir https://github.com/DISIC/sill/issues/25 et https://github.com/DISIC/sill/issues/21 : pas besoin d'une nouvelle catégorie pour l'instant. Les organismes publics hors de l'administration centrale pourront éventuellement déclarer qu'elles sont utilisatrice d'une souche libre via l'interface du SILL.
