### ISSUE TITLE
Distinguer deux rôles : "référent" et "utilisateur"

### ISSUE THREAD

**Issue by bzg** [DISIC/sill#21]
Aujourd'hui, un référent est une personne dont le nom n'apparaît pas publiquement sur le SILL mais qui est la personne ressource pour les groupes MIM quand ceux-ci cherchent des informations sur une souche.  Aucune souche n'entre dans le SILL sans référent.

La proposition consiste à distinguer deux rôles :

-   **Référent:** la personne « porte » la souche dans les groupes MIM.

-   **Utilisateur (ou « porteur »):** la personne se déclare utilisateur d'une souche qui est soit *recommandée* (`R`) soit simplement *utilisée* (`U`) cf. la proposition #0.

Une souche pourrait entrer en *recommandation* (`R`) seulement si elle a un *référent*.  Mais une souche portée seulement par un *utilisateur* pourrait entrer en *observation* (`O`) et/ou en *utilisation* (`U`).

**Comment by fanetk** [comment]
Intéressant car cela permet de valoriser, humainement parlant, les personnes impliquées sur les projets, de les faire "exister".
Publier les noms des "référents" que pour celles et ceux qui le souhaite (et qd c'est possible/sécurité etc.)
De toute façon les souches sont publiques, non ? 
Pour n'importe quel développeur il sera très facile de rentrer en contacts avec les utilisateurs... parmi lesquels il y aura très certainement le/la/les référents :-)

**Comment by bzg** [comment]
Merci pour le retour !

Oui, le partage ou la publication des noms ne peut se faire qu'avec l'accord des intéressés.

Au-delà de cet accord, il faudrait que le rôle de « référent » soit valorisé à l'intérieur de l'administration: c'est aujourd'hui la partie manquante, le SILL s'étant largement construit sur le temps libre et la bonne volonté des agents.  Avoir un autre rôle « d'utilisateur » marquerait la différence entre ceux qui prennent juste le temps de déclarer l'utilisation d'un logiciel libre (avec peu de charge) et les référents, qui s'impliquent plus.

**Comment by bzg** [comment]
Après discussion avec le groupe MIMO et partage avec le groupe MIM noyau, il ne paraît pas opportun de distinguer ces deux niveaux pour l'instant.  La recommandation des souches libres doit continuer d'émaner de l'administration centrale.

Un mécanisme pourra exister sur la future interface du SILL pour qu'un organisme hors de l'administration centrale puisse se déclarer utilisatrice de la souche.
