### ISSUE TITLE
Publier le sill sur sill.etalab.gouv.fr

### ISSUE THREAD

**Issue by bzg** [DISIC/sill#23]
Le SILL est aujourd'hui publié par les groupes MIM en PDF dans sa version stable.

Il est aussi publié sur ce dépôt comme une version de travail.

La publication du SILL sur un sous-domaine d'Etalab répondrait en partie au problème du portage officiel du SILL par la DINSIC.  L'outil de publication devrait aussi permettre de gérer les demandes d'entrée dans le SILL et l'harmonisation du travail des trois groupes MIM\*.

**Comment by kuczynski** [comment]
pour rappel: le SILL est également publié sur le [comptoir du libre](https://sill.comptoir-du-libre.org).
ADULLACT se porte volontaire pour aider à faire vivre sill.etalab.gouv.fr

**Comment by bzg** [comment]
L'idée est qu'il s'agisse à la fois d'une interface de publication _et_ d'édition collaborative permettre de soumettre une nouvelle souche et de suivre sa validation. C'est encore en développement, je vise la fin de l'année.

**Comment by fanetk** [comment]
Qu'il y ait une "industrialisation" serait vraiment pertinent et merci bzg si tu travailles dessus. 
Ce point rejoint d’ailleurs le thread sur les "cas d'usages" qui pourrait être pensé de concert avec le process de soumission, d'animation, de contrôle...mais pour le moment un pdf (ODF) est franchement suffisant (+html et epub peut etre?).  
Suffisamment industrialisé de façon à pouvoir sortir une version tous les 6 mois serait top et en // disposer d'informations, des cas, des ref, forges etc... Pour ce dernier périmètre ça pourrait être publié, géré par etalab.gouv.fr, ça semble tout à fait logique.
Pour le "SILL" en tant que "référentiel", il me semble important que ça reste sous la responsabilité du groupe MIM (publication)

@kuczynski oui il y a le comptoir est c'est tout à fait naturel et logique pour moi que le SILL soit dedans :-)

**Comment by bzg** [comment]
Ce sont de toutes façons les groupes MIM qui restent à la manoeuvre, je ne viens qu'en support et coordination/animation.

Mon hésitation aujourd'hui sur l'« industrialisation » est celle-ci: faut-il une interface web dédiée permettant de gérer une partie privée et une partie publique, ou bien le contenu du SILL peut-il évoluer entièrement en public?

Le SILL pourrait simplement être un fichier `.yml` avec les bonnes métadonnées, des liens vers les cas d'usage, etc., le tout rendu lisible via un page web minimaliste. En testant cette idée auprès des groupes MIM, j'ai eu deux retours: (1) les informations privées sont indispensables (les « référents » ne veulent pas forcément être connus publiquement) et (2) l'envoi de contributions via Git(Hub) peut en freiner beaucoup.

L'idée pour l'instant est de voir si je peux faire une interface minimaliste d'ici la fin de l'année, ce qui n'empêche pas un travail de mise en forme du SILL actuel comme fichier `.yml`.

**Comment by bzg** [comment]
Fait en version alpha - ne pas diffuser largement.
