### ISSUE TITLE
Publier des cas d'usage et des informations sur l'utilisation

### ISSUE THREAD

**Issue by bzg** [DISIC/sill#24]
Si l'entrée d'un logiciel libre au niveau *recommandé* (`R`) dépend de l'existence d'informations publiques sur son utilisation effective par un ministère ou un organisme public, il faut commencer à publier ce genre d'informations quelque part.

**Comment by fanetk** [comment]
Bonsoir, 
en ce qui concerne ce type de publications cela pourrait être confié à "Etalab" cf https://github.com/DISIC/sill/issues/23
fa

**Comment by bzg** [comment]
Etalab pourrait aider au niveau de la mise en forme, de l'éditorialisation et de la publication - mais ce serait inefficace qu'Etalab doivent aller chercher les informations, ça ne marcherait pas. Il faut encourager les administrations à partager ces retours d'expérience - ce n'est pas simple, c'est beaucoup de travail, mais j'espère qu'on pourra avancer.

**Comment by bzg** [comment]
Les améliorations du SILL seront gérées sur un autre dépôt, celle-ci est bien notée.
