### ISSUE TITLE
Ouvrir (tous?) les niveaux à tous les organismes publics

### ISSUE THREAD

**Issue by bzg** [DISIC/sill#25]
Aujourd'hui, les souches présentes dans le SILL sont utilisées dans les ministères centraux, qu'elles soient en recommandation ou en observation.

Nous pouvons envisager d'ouvrir le nouveau niveau U à tous les organismes publics, voire même tous les niveaux à tous les organismes publics, au-delà des seuls ministères centraux.

**Comment by fanetk** [comment]
Le SILL est publique :-) est sa valeur vient du fait qu'il concerne l'ensemble des ministères.
J'ai peur que si le niveau U "s'ouvre" à l'ensemble des collectivités nous perdions clairement en lisibilité et pertinence (+ orientés sur les métiers, important aussi...). 
Tu parles "d'organismes publics" perso à partir du moment tu as une "tutelle" / ministère il est possible de participer au SILL ? Me trompes-je ? 

et puis il existe deja https://comptoir-du-libre.org/ qui est pas mal du tout :-)

**Comment by bzg** [comment]
Pour être prudent, on pourrait effectivement commencer à n'ouvrir le niveau U (« en usage ») que pour les ministères centraux, voire si cela prend et si des gens acceptent d'être référent pour des logiciels libres couramment utilisés.

Et effectivement, si le https://comptoir-du-libre.org/ fait déjà le travail de référencement de l'existant en usage dans les collectivités, pas besoin d'intégrer ça au SILL.

**Comment by bzg** [comment]
Après discussion avec le groupe MIMO et partage avec le groupe MIM-noyau, il ne paraît pas opportun d'ouvrir tous les niveaux à tous les organismes publics pour l'instant, cela ferait trop de doublon avec le https://comptoir-du-libre.org.
