### ISSUE TITLE
Intégrer Zotero dans le SILL

### ISSUE THREAD

**Issue by fcuignet** [DISIC/sill#27]
Bonjour,
Serait il possible d'intégrer le gestionnaire de citation zotero www.zotero.org ?
Cordialement

**Comment by bzg** [comment]
Bonjour, oui, bonne idée, mais cela doit attendre la refonte pour qu'une catégorie "en usage" apparaisse (voir [cette issue](https://github.com/DISIC/sill/issues/20)).

**Comment by bzg** [comment]
Les propositions d'ajout dans le SILL vont être gérées autrement à partir de 2022.  Nous avons bien noté celle-ci.
