### ISSUE TITLE
Ajouter des composants utilisés dans les projets IAM

### ISSUE THREAD

**Issue by coudot** [DISIC/sill#28]
Bonjour,

nous déployons souvent pour les administrations et collectivités locales les logiciels suivants qui ne sont pas encore référencés dans le SILL :
* LSC : https://lsc-project.org/
* LTB Self Service Password : https://ltb-project.org/documentation/self-service-password
* LTB White Pages : https://ltb-project.org/documentation/white-pages

**Comment by bzg** [comment]
Merci pour l'information ! Avec les évolutions envisagées sur le SILL, nous n'en sommes pas encore à savoir comment intégrer les soumissions, mais j'espère que nous pourrons traiter ça dans les mois qui viennent.

**Comment by coudot** [comment]
Merci pour ta réponse. L'idée était aussi de bien identifier une catégorie "IAM" dans le SILL. Dans la SILL 2019, en cherchant IAM on ne trouve que KeyCloak, et en cherchant SSO on ne trouve que LL::NG, ce qui n'est pas très cohérent.

**Comment by bzg** [comment]
Salut @coudot - j'ai bien noté cette idée.  Je ferme les issues sur ce dépôt, car le SILL va être refondu très bientôt.  On a bien archivé et en tête les demandes d'ajout ou de modification, tu devrais recevoir des nouvelles d'ici fin février sur le nouveau SILL je pense.
