### ISSUE TITLE
Ajout de SonarQube comme logiciel parent

### ISSUE THREAD

**Issue by alban-auzeill** [DISIC/sill#3]
Bonjour,
Concernant "Conception & Développement/Qualité et sécurité du code source" des plugins de SonarQube sont listés (FindBugs, CheckStyle, Pmd) mais avec la formulation actuelle SonarQube ne semble pas être listé en tant que tel.
De plus, il pourrait être précisé que SonarCloud (hébergement de SonarQube dans le 'cloud') offre plus de fonctionnalités (8 langages de plus, gestion des pull requests, détection de failles de sécurité) que SonarQube Community Edition, tout en étant également gratuit pour les projets dont le code est public.

**Comment by bzg** [comment]
Bonjour, merci pour ce retour. Je l'ai fait suivre aux groupes qui composent le SILL. Cela me semble logique aussi de mettre SonarQube en logiciel parent. Pour ce qui est d'ajouter la mention d'un logiciel non-libre, ce n'est pas dans la finalité de ce document, les utilisateurs peuvent trouver l'information par eux-mêmes.

**Comment by bzg** [comment]
Fait, merci !
