### ISSUE TITLE
Ajout de OpenShot Video Editor

### ISSUE THREAD

**Issue by XanderLeaDaren** [DISIC/sill#30]
https://fr.wikipedia.org/wiki/OpenShot_Video_Editor

**Comment by bzg** [comment]
Merci ! Connaissez-vous une administration utilisatrice (de préférence un ministère) ? Un contact dans une administration/ministère qui pourrait répondre à cette question ?  Pouvez-vous donner un lien vers le fichier de licence et un autre vers le code source ?

**Comment by XanderLeaDaren** [comment]
Bonjour,
– OpenShot est présenté sur le site de l’Académie de Rouen : http://numeriques.spip.ac-rouen.fr/?Openshot
– licence GPL 3.0 d’après https://www.openshot.org/fr/about/
– code source : https://github.com/OpenShot

**Comment by bzg** [comment]
J'ai pris contact avec un référent potentiel.
