### ISSUE TITLE
Ajout de GeoGebra

### ISSUE THREAD

**Issue by XanderLeaDaren** [DISIC/sill#31]
https://fr.wikipedia.org/wiki/GeoGebra

**Comment by bzg** [comment]
Merci ! Connaissez-vous une administration utilisatrice (de préférence un ministère) ? Un contact dans une administration/ministère qui pourrait répondre à cette question ?  Pouvez-vous donner un lien vers le fichier de licence et un autre vers le code source ?

**Comment by XanderLeaDaren** [comment]
Bonjour,
– GeoGebra est présenté sur le site de la DSDEN de l’Académie d’Amiens : http://ash.dsden02.ac-amiens.fr/125-geogebra.html
– licence : https://www.geogebra.org/license
– sources : http://dev.geogebra.org/trac/wiki/SourcesForUsedLibraries

**Comment by bzg** [comment]
Les propositions d'ajout dans le SILL vont être gérées autrement à partir de 2022.  Nous avons bien noté celle-ci.
