### ISSUE TITLE
Ajout de Scratch

### ISSUE THREAD

**Issue by XanderLeaDaren** [DISIC/sill#32]
https://fr.wikipedia.org/wiki/Scratch_(langage)

**Comment by bzg** [comment]
Merci ! Connaissez-vous une administration utilisatrice (de préférence un ministère) ? Un contact dans une administration/ministère qui pourrait répondre à cette question ?  Pouvez-vous donner un lien vers le fichier de licence et un autre vers le code source ?

**Comment by XanderLeaDaren** [comment]
Bonjour,
– Scratch est documenté par l’Académie de Montpellier : http://disciplines.ac-montpellier.fr/mathematiques/des-tic-pour-des-maths/logiciels/scratch
– licence CC-BY-SA 2.0 d’après https://scratch.mit.edu/terms_of_use
– code source : https://github.com/LLK/scratch-gui et https://github.com/LLK/scratch-flash

**Comment by bzg** [comment]
Merci !

**Comment by bzg** [comment]
Les propositions d'ajout dans le SILL vont être gérées autrement à partir de 2022.  Nous avons bien noté celle-ci.
