### ISSUE TITLE
Ajout de Gramps

### ISSUE THREAD

**Issue by XanderLeaDaren** [DISIC/sill#35]
https://fr.wikipedia.org/wiki/Gramps

**Comment by bzg** [comment]
Merci ! Connaissez-vous une administration utilisatrice (de préférence un ministère) ? Un contact dans une administration/ministère qui pourrait répondre à cette question ?  Pouvez-vous donner un lien vers le fichier de licence et un autre vers le code source ?

**Comment by bzg** [comment]
Les propositions d'ajout dans le SILL vont être gérées autrement à partir de 2022.  Nous avons bien noté celle-ci.
