### ISSUE TITLE
Rédiger une plaquette lisible rapidement pour l’utilisateur occasionnel

### ISSUE THREAD

**Issue by XanderLeaDaren** [DISIC/sill#36]
Mettre en avant les logiciels les plus utiles pour un utilisateur final non administrateur.

Exemple :
![ekrano-kopio 2019-09-24 à 10 16 17](https://user-images.githubusercontent.com/28948599/65494032-5dc23900-deb4-11e9-9a6e-4f05464ebfb8.jpg)

**Comment by bzg** [comment]
Bonne idée, merci. À voir comment cela peut être pris en main par le groupe MIMO qui s'occupe plus spécifiquement des logiciels de bureautique pour les agents.

**Comment by bzg** [comment]
Les améliorations du SILL seront gérées sur un autre dépôt, mais celle-ci est bien notée !
