### ISSUE TITLE
Ajout de F-Droid

### ISSUE THREAD

**Issue by XanderLeaDaren** [DISIC/sill#37]
https://fr.wikipedia.org/wiki/F-Droid

**Comment by bzg** [comment]
Merci ! Connaissez-vous une administration utilisatrice (de préférence un ministère) ? Un contact dans une administration/ministère qui pourrait répondre à cette question ?  Pouvez-vous donner un lien vers le fichier de licence et un autre vers le code source ?

**Comment by XanderLeaDaren** [comment]
Bonjour,
– F-Droid est mentionné sur Etalab : https://mastodon.etalab.gouv.fr/@cerisara/102378938538607645 notamment avec son utilisation pour l’application OSMAnd (peut-être à ajouter comme version Android d’OpenStreetMap, d’ailleurs) ;
– licence GNU Affero 3.0 d’après https://f-droid.org/fr/about/
– source : https://gitlab.com/fdroid/fdroidclient

**Comment by bzg** [comment]
Les propositions d'ajout dans le SILL vont être gérées autrement à partir de 2022.  Nous avons bien noté celle-ci.
