### ISSUE TITLE
Ajout de Hibernate Search

### ISSUE THREAD

**Issue by rjoly** [DISIC/sill#39]
Comme Apache SolR déjà présent dans le référentiel, Hibernate Search est basé sur Lucene. C'est une couche d'abstraction en lien avec l'ORM Hibernate Core.

A ajouter dans la catégorie "Données et contenu > Moteur de recherche > Indexation et recherche plein texte"

https://fr.wikipedia.org/wiki/Hibernate#Search
https://hibernate.org/search/

**Comment by bzg** [comment]
Bonjour ! Merci pour la proposition. Avez-vous des informations sur un ministère ou un autre organisme public qui utiliserait déjà Hibernate Search ? Voire un agent public dans ce ministère ou cet organisme qui pourrait se porter référent pour ce logiciel ?

**Comment by rjoly** [comment]
Ce composant est intégré à notre socle [Igloo](https://github.com/igloo-project/igloo-parent). Nous l'utilisons notamment pour une application du MTES (Ministère de la Transition Ecologique et Solidaire). Néanmoins, je ne sais pas s'il existe des directives concernant son utilisation, je sais simplement que c'est un composant relativement "mainstream", que nous utilisons depuis des années, qui évolue régulièrement tout en offrant une bonne stabilité.

Je vous fait parvenir en privé les informations sur notre application pour le Ministère et les coordonnées de mon contact technique.

**Comment by bzg** [comment]
Merci beaucoup.

**Comment by bzg** [comment]
Les propositions d'ajout dans le SILL vont être gérées autrement à partir de 2022.  Nous avons bien noté celle-ci.
