### ISSUE TITLE
Ajout de Lazarus et CodeTyphon

### ISSUE THREAD

**Issue by ghost** [DISIC/sill#4]
Bonjour,
Je développe en pascal depuis 1983.
Donc, mon institut a fait l'acquisition d'une licence Delphi depuis plusieurs années.
Mais j'utilise aussi comme outil libre :
Lazarus
https://www.lazarus-ide.org/
et CodeTyphon
https://www.pilotlogic.com/
Tous les deux basés sur le compilateur FreePascal et permettant de faire de la cross-compilation . 
Je suggère  de faire apparaitre ces outils dans l'onglet "SILL MIMDEV" pour la "Conception & développement". 

Cordialement.

**Comment by bzg** [comment]
C'est bien noté, merci beaucoup.  Jusqu'à présent, les "souches" présentées dans le SILL ont besoin d'être portées par un "référent" en administration centrale, mais ce critère pourra évoluer. La demande est bien notée en tous cas.

**Comment by bzg** [comment]
Les propositions d'ajout dans le SILL vont être gérées autrement à partir de 2022.  Nous avons bien noté celle-ci.
