### ISSUE TITLE
Ajouter FusionDirectory dans les solutions IAM

### ISSUE THREAD

**Issue by bilbo-the-hobbit** [DISIC/sill#41]
###  Nom
FusionDirectory 

### urls
site web : https://www.fusiondirectory.org/

forge : https://gitlab.fusiondirectory.org

License : https://gitlab.fusiondirectory.org/fusiondirectory/fd/-/blob/fusiondirectory-1.3/LICENSE

### Fonctionnalites

FusionDirectory https://www.fusiondirectory.org/ est une solution de gestion des identités fortement utilise dans l'enseignement Supérieur Recherche, elle est référencé au CNLESR http://groupelogiciel.cnlesr.fr/ .

Elle permet de moderniser et simplifier la gestion des identités https://www.fusiondirectory.org/fonctionnalites/

### Referent
Alexis Michon, ibcp 
Mathias Souplaut, inalco

Merci

**Comment by bzg** [comment]
Merci !

**Comment by bilbo-the-hobbit** [comment]
bonjour @bzg,

j'ai mis a jour le ticket suivant le template et ajoute le referent qui va s'en occuper

Bonne apres-midi

**Comment by bzg** [comment]
J'ai pris contact par mail avec @amichon69 - merci !

**Comment by bzg** [comment]
FusionDirectory est désormais dans le SILL: https://sill.etalab.gouv.fr/fr/software?id=206
