### ISSUE TITLE
Ajout de RStudio

### ISSUE THREAD

**Issue by bzg** [DISIC/sill#44]
En recherche d'un référent.

**Comment by bellice** [comment]
Ok pour être le référent de RStudio.

**Pour info :**
Code source : https://github.com/rstudio/rstudio
License AGPL v3 : https://rstudio.com/products/rstudio/#rstudio-desktop

**Comment by bzg** [comment]
Merci pour les infos !  J'ai mis à jour la page https://disic.github.io/sill/index.html pour donner des précisions sur les critères d'admission dans le SILL et ce qu'implique d'être « référent » pour un logiciel.  Si tu as des questions n'hésite pas à me dire, ici ou par mail.

**Comment by bzg** [comment]
RStudio est désormais présent sur https://sill.etalab.gouv.fr. Merci !
