### ISSUE TITLE
Mise à jour version de Squash TM

### ISSUE THREAD

**Issue by flzara** [DISIC/sill#49]
Squash TM a monté de version et propose désormais la version 1.20 depuis juin 2019

- URL du site : http://www.squashtest.com
- Code source sur Bitbucket : https://bitbucket.org/nx/squashtest-tm/src/default/
- Licence : LGPL v3 : https://bitbucket.org/nx/squashtest-tm/src/default/COPYING.txt
- repo des binaires : http://repo.squashtest.org/distribution/

Plusieurs ministères l'utilisent sur des version plus récentes. Parmi ceux qui se sont manifestés et ont demandé du support (impossible de savoir pour ceux téléchargeant sans se manifester)

- Groupement Interministeriel de Contrôle  → version 1.20
- Ministère de l'Éducation Nationale  → version 1.20
- Minefi (Secrétariat Général) → version 1.18, peut-être plus

Je ne sais pas si je peux donner publiquement les noms des référents ici, mais je les tiens disponible en privé.

**Comment by bzg** [comment]
Bonjour Florent,

Merci pour l'issue.

Voici mon email pour m'envoyer le nom des référents, à ne pas diffuser publiquement : `bastien.guerry@data.gouv.fr` - j'ai précisé le rôle des référent dans la [page d'accueil](https://disic.github.io/sill/), ceux-ci sont volontaires et il ne suffit pas d'être le contact d'un logiciel dans une administration centrale pour en être le « référent ».

Bonne soirée !

**Comment by flzara** [comment]
Réponse envoyée par email !

**Comment by bzg** [comment]
Les versions de Squash TM ont été mises à jour - merci de vérifier sur https://sill.etalab.gouv.fr sur tout est OK et de me demander de rouvrir l'issue si besoin.
