### ISSUE TITLE
Logiciel concerné : mongodb

### ISSUE THREAD

**Issue by bzg** [DISIC/sill#58]
MongoDB

La licence de mongodb ne figure plus parmi les licences libres de l'OSI ou de la FSF.

**Comment by dzc34** [comment]
ce commit https://github.com/DISIC/sill/commit/cb106fb38f1471b2cab422a7b325a30dbcc4ef91 semblait supprimer MongoDB. mais il est toujours dans la dernière version du fichier.

**Comment by bzg** [comment]
C'est corrigé, merci !
