### ISSUE TITLE
Intégrer des critères écoresponsables au sein du SILL

### ISSUE THREAD

**Issue by NicolasLeport** [DISIC/sill#8]
Tenir compte des impacts environnementaux et sociaux des logiciels libres de droits avant de les conseiller (SILL). Proposer des critères de notation tel que les droits humains, le code du travail, la présence de labels ou non, la source d'énergie utilisée, l'impact carbone de la conception et de l’utilisation du logiciel.

**Comment by bzg** [comment]
Cf. https://github.com/DISIC/sill/issues/22 - ces informations sur l'éco-responsabilité des souches présentées dans le SILL pourraient être ajoutées dans un premier temps à titre d'informations supplémentaires, sans être un critère obligatoire pour le passage en recommandation.

**Comment by fanetk** [comment]
Bonsoir, un ouvrage/travail pertinent sur le sujet : https://www.greenit.fr/2019/09/10/sobriete-numerique-les-cles-pour-agir/ pour info sur le coté GreenIT. D'une manière générale un code ouvert (LL) est par essence optimisé par les contributeurs, réutilisable, distribuable etc et de ce fait intègre les critères que nous pourrions donner à un logiciel). 
Du coup je ne pense pas nécessaire qu'il y ait un critère spécifique à ce sujet, mais une explication claire à ce sujet en intro du SILL. OK avec ta proposition bzg

L'éco-responsabilité du numérique est un très gros sujet pour la DINSIC mais pas pour sur le SILL (ou MIMO) tel que j'ai compris leurs misions et objectifs. Il faut simplement une volonté politique mais je ne vois aucun signe de ce coté :-(

**Comment by bzg** [comment]
Une première piste pourrait être d'encourager la DINSIC à publier une évaluation du type [ecoindex](http://www.ecoindex.fr) pour les sites des organismes publics. Cela alerterait sur les sites trop lourds et trop complexes. C'est tangent à la question de l'accessibilité, sujet par ailleurs bien porté par la DINSIC.

J'ai un début d'[expérimentation](https://gouvfr.bzg.fr/), mais j'attends de faire quelque chose de plus propre.

**Comment by bzg** [comment]
Les améliorations du SILL seront gérées sur un autre dépôt, celle-ci est bien notée.
