### ISSUE TITLE
Amélioration : Information sur l'accessibilité par logiciel

### ISSUE THREAD

**Issue by JulietteS** [DISIC/sill#85]
Chaque administration utilise une bonne partie des logiciels du SILL. 
Le respect du RGA est une information qu'on pourrait mutualiser davantage. Serait-il possible de l'ajouter au modèle de données, de manière à avoir facilement accès à l'information ?

**Comment by bzg** [comment]
Oui - le respect du RGI et RGA fait partie des informations optionnelles mais souhaitables.

Voir [cette issue](https://github.com/DISIC/sill/issues/22) qui a permis d'aboutir à [cette formulation](https://disic.github.io/sill/#orgb2d72ab) - voir aussi [cette soumission](https://github.com/DISIC/sill/issues/43) qui présente une évaluation de ce critère pour le logiciel proposé.

Nous sommes trop près de la publication du SILL 2020 pour intégrer cela dans le [csv](https://github.com/DISIC/sill/blob/master/2020/sill-2020.csv) maintenant (car nous ne pourrions pas facilement renseigner le champ pour les logiciels du SILL), mais cela fait partie des priorités pour la suite.

Au passage et pour info, nous devons aussi passer du csv à un outil de partage des informations où pourront se connecter les référents des groupes MIM, l'outil aidera à mettre en valeur ces informations « optionnelles ».

**Comment by bzg** [comment]
Les améliorations du SILL seront gérées sur un autre dépôt, celle-ci est bien notée.
