### ISSUE TITLE
Nouveau logiciel : Captura

### ISSUE THREAD

**Issue by maaaaz** [DISIC/sill#90]
Bonjour vous recommandez aujourd'hui "OBS Studio" pour la captation video.
Je vous propose Captura, qui est encore plus simple d'utilisation

https://mathewsachin.github.io/Captura/
https://framalibre.org/content/captura

Non

**Comment by bzg** [comment]
Bonjour, merci pour la soumission. Avez-vous un contact avec un agent public dans la fonction publique d'Etat ou hospitalière qui pourrait se porter [référent](https://disic.github.io/sill/#org9f709d7) pour ce logiciel ?  C'est une condition indispensable, les référents échangeant entre eux pour choisir les logiciels du SILL.

**Comment by maaaaz** [comment]
Malheureusement non :(

**Comment by bzg** [comment]
Ce n'est pas grave, c'est toujours utile de référencer une solution ici pour mémoire et au cas où un référent se présenterait.  Merci !

**Comment by bzg** [comment]
Les propositions d'ajout dans le SILL vont être gérées autrement à partir de 2022.  Nous avons bien noté celle-ci.
