### ISSUE TITLE
Nouveau logiciel : SDK Géoportail

### ISSUE THREAD

**Issue by lboulanger** [DISIC/sill#92]
Bonjour,

Nous souhaitons référencer l'[API JavaScript Géoportail](https://github.com/IGNF/geoportal-sdk), développée par l'[IGN](http://ign.fr/), permettant d'ajouter simplement dans un site web une carte utilisant les ressources du Géoportail (photographies aériennes, cartes topographiques, géocodage, calcul d'altimétrie, etc.).
Elle est constituée de plusieurs modules, nous souhaitons référencer dans un premier temps celui destiné au plus grand public : le kit de développement (SDK) Géoportail.

Nom du logiciel : SDK Géoportail

Description et documentation: https://geoservices.ign.fr/documentation/utilisation_web/sdk.html
Code source : https://github.com/IGNF/geoportal-sdk
Licence : [CeCILL-B](https://cecill.info/licences/Licence_CeCILL-V1_VF.pdf) (Free BSD compatible)

Référent identifié : oui

Merci d'avance.

**Comment by bzg** [comment]
Merci pour la proposition. Quelle est la version minimale à recommander ?

Pouvez-vous m'envoyer par mail (bastien.guerry @ data.gouv.fr) le contact de la personne qui serait référente ?

**Comment by bzg** [comment]
Fait: https://sill.etalab.gouv.fr/fr/software?id=201

**Comment by lboulanger** [comment]
Bonjour, 

Merci pour votre réactivité et la prise en compte de la demande !

Pour la description du logiciel dans la liste, est-ce possible d'ajouter plutôt :

**Fonction :** 
Affichage d'une carte dynamique avec les données Géoportail (ou s'il faut faire vraiment très court ou simple : Cartographie web)

**Contexte :** 
Développement web

Et ajouter les liens vers le site web (https://geoservices.ign.fr/documentation/utilisation_web/sdk.html) et le code source (https://github.com/IGNF/geoportal-sdk) comme pour d'autres logiciels (avec les icônes en bas), svp ?

Merci d'avance ! :)

**Comment by bzg** [comment]
Bonjour,

j'ai mis à jour les informations pour la description et le contexte, avec les liens indiqués.

Pour les icones en bas de chaque fiche, c'est lorsque les informations sont accessibles via une entité de [Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page): si vous créez une page Wikidata dédiée au SDK Géoportail vous pouvez ensuite m'envoyer l'identifiant de l'entité et je mettrai à jour le SILL - mais les informations actuelles sont déjà suffisantes.

Merci !

**Comment by lboulanger** [comment]
Merci pour ce retour et la prise en compte des modifications !
Bonne journée.
