### ISSUE TITLE
Nouveau logiciel : TYPO3

### ISSUE THREAD

**Issue by junfan59** [DISIC/sill#96]
TYPO3 CMS

- https://typo3.org/
- https://github.com/TYPO3/TYPO3.CMS
- Licence GNU GPL v2 pour le CMS et GNU LGPL v3 pour le langage de templating associé "Fluid".

Moi même. J'ai contacté bastien.guerry@data.gouv.fr depuis mon adresse mail professionnelle.

**Comment by bzg** [comment]
Bonjour, quelle est la version minimale recommandée par votre administration ?

**Comment by bzg** [comment]
C'est ajouté - merci !
