### ISSUE TITLE
Nouveau logiciel : JOSM

### ISSUE THREAD

**Issue by don-vip** [DISIC/sill#97]
JOSM (Java OpenStreetMap Editor)

https://josm.openstreetmap.de/
https://josm.openstreetmap.de/svn/trunk/
https://josm.openstreetmap.de/svn/trunk/LICENSE

**Comment by bzg** [comment]
Merci pour la proposition d'ajout.

Avez-vous un contact avec un agent public qui pourrait se porter référent ?  Voir [cette page](https://disic.github.io/sill/#org58fdd0a) pour quelques explications.

**Comment by don-vip** [comment]
Pas pour l'instant. J'ai fait un [appel à candidature](https://lists.openstreetmap.org/pipermail/talk-fr/2020-May/098860.html), j'espère que quelqu'un va se manifester.

**Comment by bzg** [comment]
Merci !

**Comment by don-vip** [comment]
C'est bon, l'appel a été concluant :)

**Comment by bzg** [comment]
JOSM est désormais dans le SILL : https://sill.etalab.gouv.fr/fr/software?id=207

**Comment by don-vip** [comment]
@bzg génial merci ! Juste un petit détail, "OpenStreetMap" s'écrit tout attaché, c'est possible de supprimer les espaces ?

**Comment by bzg** [comment]
C'est corrigé - merci !
