### ISSUE TITLE
Logiciel concerné : zimbra

### ISSUE THREAD

**Issue by tcataldo** [DISIC/sill#98]
Zimbra

Le logiciel zimbra ne sera désormais plus opensource à partir de sa nouvelle version, la 9:
https://wiki.zimbra.com/wiki/Zimbra_Releases/9.0.0
"There are no Open Source repositories specific to Zimbra 9."

**Comment by bzg** [comment]
J'ai ajouté une alerte dans le SILL : pourrez-vous rouvrir une issue quand Zimbra 8.x ne sera plus, d'après-vous, une solution utilisable par l'administration ?

**Comment by tcataldo** [comment]
La fin du support est autour de fin 2023, début 2024. https://www.zimbra.com/support/support-offerings/product-lifecycle/
Le temps de préparer sereinement la migration vers bluemind ;-)

**Comment by bzg** [comment]
Merci pour l'info - d'ailleurs si on trouve une administration utilisatrice de Bluemind et qui souhaite être référente, cela aiderait à référencer d'autres solutions.
